### ISSUE TITLE
Gissa hela ordet

### ISSUE THREAD

**Issue by einarpersson** [PontusLiedgren/project-1-hangman#4]
Bra jobbat Pontus, väldigt trevlig användarupplevelse (välkomstmeddelandet, gubben på slutet etc.) :clap: 

När jag spelade spelet ville jag även kunna gissa på hela ordet, det kändes lite knasigt att veta vilket ord du var ute efter men inte skrika ut det utan alltid vara tvingad till en bokstav i taget. Kan du lägga till funktionalitet för att även acceptera en ord-gissning?

**Comment by PontusLiedgren** [comment]
Fixade så att man kan gissa på hela ordet!
